name: Build APK

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        pip install --upgrade pip
        pip install buildozer cython

    - name: Build APK using Buildozer Docker
      run: |
        docker run --rm -v ${{ github.workspace }}:/home/user/hostcwd \
          -w /home/user/hostcwd \
          ghcr.io/kivy/buildozer:latest \
          /bin/bash -c "buildozer android debug"

