name: Build APK

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build-apk:
    runs-on: ubuntu-latest
    env:
      ANDROID_API: 33
      ANDROID_MINAPI: 21

    steps:
      - name: 檢出程式碼
        uses: actions/checkout@v3

      - name: 設定 Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: 安裝系統相依套件
        run: |
          sudo apt-get update
          sudo apt-get install -y zip unzip openjdk-17-jdk python3-pip python3-setuptools \
            libssl-dev libffi-dev

      - name: 安裝 Buildozer & Cython
        run: |
          python3 -m pip install --upgrade pip
          pip install buildozer cython

      - name: 安裝 Android SDK
        uses: android-actions/setup-android@v3
        with:
          packages: "platform-tools build-tools;${{ env.ANDROID_API }}.0.0 platforms;android-${{ env.ANDROID_API }}"

      - name: 安裝 Android NDK
        uses: nttld/setup-ndk@v1
        with:
          ndk-version: r25b
          link-to-sdk: true

      - name: 建置 APK
        working-directory: mygame_kivy
        run: |
          buildozer android clean
          buildozer android debug --verbose

      - name: 上傳 APK 產物
        uses: actions/upload-artifact@v4
        with:
          name: MyKivyGame-debug-apk
          path: mygame_kivy/bin/*.apk

