name: Build APK

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build-apk:
    runs-on: ubuntu-latest
    env:
      ANDROID_API: 33
      ANDROID_MINAPI: 21
      ANDROID_NDK: 25b

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'

    - name: Install system deps
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          zip unzip openjdk-17-jdk python3-pip python3-setuptools \
          libssl-dev libffi-dev

    - name: Install Buildozer & Cython
      run: |
        python3 -m pip install --upgrade pip
        pip install buildozer cython

    - name: Install Android SDK/NDK
      uses: android-actions/setup-ndk@v2
      with:
        ndk-version: ${{ env.ANDROID_NDK }}
    - name: Setup Android SDK Command‐line Tools
      run: |
        mkdir -p $HOME/Android/Sdk/cmdline-tools
        cd $HOME/Android/Sdk/cmdline-tools
        wget https://dl.google.com/android/repository/commandlinetools-linux-9477386_latest.zip -O tools.zip
        unzip tools.zip
        mv cmdline-tools latest
        yes | $HOME/Android/Sdk/cmdline-tools/latest/bin/sdkmanager --sdk_root=$HOME/Android/Sdk \
          "platform-tools" "platforms;android-${ANDROID_API}" "build-tools;33.0.0"

    - name: Configure Buildozer
      run: |
        # ensure buildozer.spec is present
        buildozer init || true

    - name: Build APK
      run: |
        buildozer android debug --quiet

    - name: Upload APK artifact
      uses: actions/upload-artifact@v3
      with:
        name: MyKivyGame-debug-apk
        path: bin/*.apk
