name: Build APK

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-22.04  # 避免 ubuntu-24 自帶新編譯鏈問題

    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y openjdk-17-jdk unzip git python3-pip \
                              autoconf automake libtool pkg-config \
                              build-essential m4
          pip install buildozer cython

      - name: Build APK
        run: |
          buildozer android clean
          buildozer android debug --log-level 2

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: MyZombieApp-APK
          path: bin/*.apk
