name: Build Kivy APK

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout source code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.11

    - name: Install system & Python dependencies
      run: |
        sudo apt update
        sudo apt install -y build-essential ccache unzip openjdk-11-jdk wget \
                            libffi-dev libssl-dev libtool automake autoconf
        python -m pip install --upgrade pip
        pip install cython buildozer

    - name: Set JAVA_HOME (optional)
      run: echo "JAVA_HOME=/usr/lib/jvm/java-11-openjdk-amd64" >> $GITHUB_ENV

    - name: Initialize Android SDK
      run: |
        mkdir -p ~/.android
        echo "sdk.dir=$HOME/.buildozer/android/platform/android-sdk" > ~/.android/repositories.cfg
        yes | buildozer android update

    - name: Build APK
      run: buildozer android debug
