name: Build Kivy APK

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.11

    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y build-essential ccache libncurses5 unzip openjdk-11-jdk wget
        python -m pip install --upgrade pip
        pip install cython buildozer

    - name: Install Android SDK and NDK
      run: |
        mkdir -p ~/.android
        echo "sdk.dir=$HOME/.buildozer/android/platform/android-sdk" > ~/.android/repositories.cfg
        yes | buildozer android update

    - name: Build APK
      run: buildozer android debug
